//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ___FILEBASENAMEASIDENTIFIER___ViewController: ___FILEBASENAMEASIDENTIFIER___InteractorInput {}

extension ___FILEBASENAMEASIDENTIFIER___Interactor: ___FILEBASENAMEASIDENTIFIER___PresenterInput {}

extension ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___ViewControllerInput {}

class ___FILEBASENAMEASIDENTIFIER___Configurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ___FILEBASENAMEASIDENTIFIER___Configurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ___FILEBASENAMEASIDENTIFIER___ViewController)
  {
    let presenter        = ___FILEBASENAMEASIDENTIFIER___Presenter()
    let interactor       = ___FILEBASENAMEASIDENTIFIER___Interactor()
    
    interactor.input     = viewController
    presenter.input      = interactor
    viewController.input = presenter
  }
}
